apiVersion: 1

deleteDatasources:
  - name: Expenses
    orgId: 1

datasources:
- name: Expenses
  type: mysql
  access: proxy
  url: db:3306
  user: $MYSQL_USER
  secureJsonData:
    password: $MYSQL_PASS
  database: $MYSQL_DB

