---
apiVersion: v1
kind: Pod
metadata:
  name: expenses
spec:
  restartPolicy: OnFailure
  containers:
    - name: expenses-bot
      image: golang:1.20
      env:
        - name: "EXPENSES_USER"
          value: "expuser"
        - name: "MYSQL_HOST"
          value: "contre.io"
        - name: "MYSQL_PORT"
          value: 3306
        - name: "EXPENSES_DB"
          value: "expdb"
        - name: "TELEGRAM_APITOKEN"
          valueFrom:
            secretKeyRef:
              name: expenses-secrets
              key: telegram-token
        - name: "EXPENSES_PASS"
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-expenses-pass
