---
apiVersion: v1
kind: Pod
metadata:
  name: expenses
spec:
  restartPolicy: OnFailure
  containers:

    - name: grafana
      image: grafana
      ports:
        - name: front
          containerPort: 3000
          hostPort: 3000
          protocol: TCP
      env:
        - name: GF_INSTALL_PLUGINS
          value: grafana-piechart-panel
        - name: GF_PANELS_DISABLE_SANITIZE_HTML
          value: true
        - name: "EXPENSES_USER"
          value: "expuser"
        - name: "EXPENSES_DB"
          value: "expdb"
        - name: "EXPENSES_PASS"
          value: "password"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false

    - name: mysql
      image: mysql
      ports:
        - name: front
          containerPort: 3306
          hostPort: 3306
          protocol: TCP
      env:
        - name: "EXPENSES_USER"
          value: "expuser"
        - name: "EXPENSES_DB"
          value: "expdb"
        - name: "EXPENSES_PASS"
          value: "password"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "toor"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities: {}
        privileged: false
        readOnlyRootFilesystem: false
