---
apiVersion: v1
kind: Pod
metadata:
  name: expenses
spec:
  restartPolicy: OnFailure
  containers:
    - name: telegrambot
      image: build
      ports:
        - name: front
          containerPort: 3000
          hostPort: 3000
          protocol: TCP
      env:
        - name: "EXPENSES_USER"
          value: "expuser"
        - name: "EXPENSES_USER"
          value: "expuser"
        - name: "EXPENSES_DB"
          value: "expdb"
        - name: "EXPENSES_PASS"
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-expenses-pass
      volumeMounts:
        - mountPath: /
          name: local-users
  volumes:
  - name: local-users
    hostPath:
      path: /mnt/SSD/data/
      type: ''


